// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWDnW05k-_KWE70QHRk5BllsvVTM4dsTo',
    appId: '1:578254388177:web:ff623f197705c08f3f7ef0',
    messagingSenderId: '578254388177',
    projectId: 'dhgc-firebase-authentication',
    authDomain: 'dhgc-firebase-authentication.firebaseapp.com',
    storageBucket: 'dhgc-firebase-authentication.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi9OyLnZRR3L6NkKvZ6v8nLQlLtcRMsq0',
    appId: '1:578254388177:android:c54001e4af0059023f7ef0',
    messagingSenderId: '578254388177',
    projectId: 'dhgc-firebase-authentication',
    storageBucket: 'dhgc-firebase-authentication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAczPTHwqyAQXeUDog16JjRnbfJYSg0kEE',
    appId: '1:578254388177:ios:080460945cc3a4863f7ef0',
    messagingSenderId: '578254388177',
    projectId: 'dhgc-firebase-authentication',
    storageBucket: 'dhgc-firebase-authentication.firebasestorage.app',
    iosBundleId: 'com.example.dhgcChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAczPTHwqyAQXeUDog16JjRnbfJYSg0kEE',
    appId: '1:578254388177:ios:080460945cc3a4863f7ef0',
    messagingSenderId: '578254388177',
    projectId: 'dhgc-firebase-authentication',
    storageBucket: 'dhgc-firebase-authentication.firebasestorage.app',
    iosBundleId: 'com.example.dhgcChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWDnW05k-_KWE70QHRk5BllsvVTM4dsTo',
    appId: '1:578254388177:web:3c3f87f55155cae33f7ef0',
    messagingSenderId: '578254388177',
    projectId: 'dhgc-firebase-authentication',
    authDomain: 'dhgc-firebase-authentication.firebaseapp.com',
    storageBucket: 'dhgc-firebase-authentication.firebasestorage.app',
  );
}
